### ISSUE TITLE
Make the centos image as the default

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#101]
Currently the default image for the spark operator is based on Alpine linux with JRE. The image is pretty small, but doesn't have the standard package manager => limited signing/checksums, etc.

Let's make the centos image as the default option. The test suite in Travis CI should be also running the centos image.

**Comment by yaroslavm** [comment]
Hi @Jiri-Kremser , I can take care of this one. What do you think is better to do with alpine image? Provide it as an option with _-alpine_ suffix as you do for now with centos or remove alpine image completely?

**Comment by Jiri-Kremser** [comment]
@yaroslavm Thank you for looking into this and feel free to take this one. `-alpine` suffix would be good, no I think, removing it completely is not wanted.

please make sure the change is also made to these files:

- `README.md`
- `Makefile`
- `.travis/.travis.release.images.sh`

I hope, I didn't forget anything.

**Comment by yaroslavm** [comment]
@Jiri-Kremser done, looks better now. What do you think?

**Comment by Jiri-Kremser** [comment]
done in #102
