### ISSUE TITLE
smarter state reconciliation that will work with restarted operator

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#115]
Currently, if the operator is restarted or pod simply crashes and meanwhile some CM or CR is "C~R~UDed", then after the operator is up and running again, it basically lost that 1 event and end up in inconsistent state.

**Comment by zroubalik** [comment]
For operator that uses CR incosistent state occurs even if theres no "CRUD" operation running. It simply doesn't recover from failure, but operator that uses CM recovers without a problem.

How to reproduce:
1. deploy operator
2. create spark cluster via CR
3. wait till cluster is running
4. delete operator's pod
5. new pod is rescheduled, but there's error message in the log:
`2018-10-12 13:40:21 ERROR WatchConnectionManager:272 - Could not deserialize watch event: {"type":"ADDED","object":{"apiVersion":"radanalytics.io/v1","kind":"sparkcluster","metadata":{"clusterName":"","creationTimestamp":"2018-10-12T13:39:35Z",...`

**Comment by Jiri-Kremser** [comment]
related PR on abstract operator repo - https://github.com/jvm-operators/abstract-operator/pulls

**Comment by Jiri-Kremser** [comment]
and here https://github.com/radanalyticsio/spark-operator/pull/141

**Comment by Jiri-Kremser** [comment]
done in #141
