### ISSUE TITLE
Clarify relationship to similar projects in readme

### ISSUE THREAD

**Issue by sharebear** [radanalyticsio/spark-operator#116]
Reading through the other issues there are some references to the [GCP Spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) and within the radanalyticsio there is also a [kubespark-operator](https://github.com/radanalyticsio/kubespark-operator), I feel that it could be useful if the README had a section clarifying the relationship to the other projects and for which use-cases this operator would be the correct one to use.

**Comment by elmiko** [comment]
thanks for bringing this up @sharebear, i think we should definitely have a link to the GCP spark operator with a description of the differences.

as for the kubespark-operator, i _think_ that project is deprecated and we should probably mothball it, but i will investigate.

**Comment by elmiko** [comment]
i am closing this issue as we have addressed the main concern.

@sharebear if you feel what we have put into the readme is insufficient, please create a new issue with the concerns.

thanks!

**Comment by sharebear** [comment]
Sorry for the slow response but yeah, lgtm

**Comment by elmiko** [comment]
no worries, took us awhile to get around to addressing it!

 thanks for taking a look =)
