### ISSUE TITLE
Add an option to enable Spark Prometheus metrics

### ISSUE THREAD

**Issue by vpavlin** [radanalyticsio/spark-operator#124]
radanalytics.io Spark images have ability to expose Prometheus metrics (see  https://github.com/radanalyticsio/openshift-spark/blob/master/spark-metrics-template.yaml#L75). Add a config option to do the same with operator.

Right now I can add environment variable to enable metrics, but have no way to open a port for Prometheus to scrape spark instances.

Ideally the solution should allow to configure this by a single option (not something like "expose port & add env variable" in spark operator CM/CR)

**Comment by Jiri-Kremser** [comment]
done in #133
