### ISSUE TITLE
Quickstart failed

### ISSUE THREAD

**Issue by mjschmidt** [radanalyticsio/spark-operator#125]
### Describe the problem:

  * With couple of sentences describe the problem and its context.

#### Steps to reproduce:

  1.  start a minikube with no vm (basically the kubeadm version of minikube everyone uses now)
  2. clone the project
  3. kubectl apply -f manifest/operator.yaml
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

![image](https://user-images.githubusercontent.com/6544930/47273506-49b6de80-d563-11e8-9880-f50df4214427.png)

![image](https://user-images.githubusercontent.com/6544930/47273511-5e937200-d563-11e8-8de6-dd363c7bf5b6.png)

![image](https://user-images.githubusercontent.com/6544930/47273516-78cd5000-d563-11e8-8cef-55b67a02a487.png)

  
#### Expected Results:

  * What did you expect to happen?

I expected the operator to come up normally. What is going on?

**Comment by Jiri-Kremser** [comment]
(duplicate of #127)
