### ISSUE TITLE
custom image definition is not used by the executors

### ISSUE THREAD

**Issue by mmonro** [radanalyticsio/spark-operator#146]
### Describe the problem:

When configuring a custom image definition the driver pod observes the custom image, but the executor pods still try to use jkremser/openshift-spark:2.3-latest which is not accessible in a disconnected environment.  To work around this issue you can manually update the image definition in the replication controller once the job is kicked off.

#### Steps to reproduce:

1. Load the spark image into the internal docker registry, in our case named docker-registry.default.svc:5000/rad-spark-operator/openshift-spark:2.3-latest

2. Use a custom image definition such as the following:

# cat rad-spark-app.yaml

apiVersion: v1

kind: ConfigMap

metadata:

  name: my-spark-app

  labels:

    radanalytics.io/kind: sparkapplication

data:

  config: |-

    image: docker-registry.default.svc:5000/rad-spark-operator/openshift-spark:2.3-latest

    mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar

    mainClass: org.apache.spark.examples.SparkPi
 
 
  
#### Observed Results:

The executor pods still try to pull the jkremser/openshift-spark:2.3-latest image which is hardcoded somewhere
  

#### Expected Results:

The driver and executor pods should observe the custom image definition

**Comment by Jiri-Kremser** [comment]
done in https://github.com/radanalyticsio/spark-operator/commit/6c318c66ea744e717ac7de3fdf05590ce9e754c9

Thanks for reporting the issue
