### ISSUE TITLE
spark apps: support python and scala

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#157]
currently it's Java only

UPDATE: and python

**Comment by reynoldsm88** [comment]
I can look into the Scala side @Jiri-Kremser. I'm currently learning the code right now, can you give me any general advice or hints to look to where to get started?

**Comment by Jiri-Kremser** [comment]
@reynoldsm88 
Thanks for looking, as we were talking about it, it looks like the Scala doesn't need any special treatment and it works the same way as Java all is needed is specifying:

* `mainApplicationFile` (path to jar)
* `mainClass` (fully qualified class name)

..in the Spark App manifest. 

So I am closing this issue, sorry for the confusion. What's still missing is the support for the R language. But it would deserve it's own issue, because it will be probably more difficult.
