### ISSUE TITLE
Use CamelCase names for the CRDs

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#179]
Currently the marketplace in OCP 4.0 displays our CRDs as "parkapplication" and "parkcluster". There is a bug in their web ui, however it would be better to align the naming with other operators. It is much more common to use `CamelCaseName` instead of `lowercasename`.

So this issue is about: 
* `sparkcluster` -> `SparkCluster`
* `sparkapplication` -> `SparkApplication`

It would probably also require some work in the abstract operator library (namely, the code that is responsible for creating the CRDs - https://github.com/jvm-operators/abstract-operator/blob/bf0e0649fb69367040b200ae19bebe371be89d3c/src/main/java/io/radanalytics/operator/common/crd/CrdDeployer.java#L22)

**Comment by elmiko** [comment]
this fix in the abstract-operator will help, https://github.com/jvm-operators/abstract-operator/pull/29

**Comment by elmiko** [comment]
@Jiri-Kremser i think we can close this issue now
