### ISSUE TITLE
Make the default image for spark clusters and for spark apps configurable

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#186]
Both images are customizable via fields in the CR or CM, if they are not specified the defaults are taken from the JSON schema definition. It may be good enhancement to make the default values for the images configurable on the operator level. For instance if an environment variable, say, `DEFAULT_SPARK_{CLUSTER|APP}_IMAGE` is defined, it would be the default for newly created clusters/apps. Of course the explicitly specified `image: foo:latest` in the CR or CM will still have the highest precedence.

**Comment by elmiko** [comment]
as i am examining this issue there seems to be a corner case that is proving difficult to work around.

example:

1. spark-operator has been started with env variable `DEFAULT_SPARK_CLUSTER_IMAGE=foo`
1. the default CRD defines `bar` as the default image
1. the env variable will override the CRD default
1. user specifies `customImage: bar` in their CRD schema

how do we know that the user wanted the `bar` image and not override?

i'm not sure if adding the environment variable is the best approach for this, maybe we should focus more on changing the CRD schema if a user wants to change the default. i'm curious for your thoughts @Jiri-Kremser.

**Comment by Jiri-Kremser** [comment]
> how do we know that the user wanted the `bar` image and not override?

based on the precedency rules:
* the default specified in the JSON schema (build time thing, can't be changed for given version)
* the default specified in the env variable (run-time thing, can be changed by `oc edit` or `oc env`)
* the `customImage` specified in the custom resource or config map (highest priority, no default value is applied here)

there can be 4 cases:
1) if both the env variable and the `customImage` in CR are set in the same time, then the value for `customImage` will take precedence,
2) if the env. variable is set and there is new CR being created w/o the `customImage`, then the default from env. variable is used
3) env. variable has no value, and also there is no `customImage` in the new CR, then the default from the JSON schema is used
4) no env. variable and there is a new CR with the `customImage` being set, then the `customImage` value is used

It's not so confusing, imho

**Comment by elmiko** [comment]
>     2\. if the env. variable is set and there is new CR being created w/o the `customImage`, then the default from env. variable is used

i believe this part is what causes the confusion because the way the schema is specified the `customImage` will get the default value if it is not specified by the user (assuming i am reading this correctly https://github.com/radanalyticsio/spark-operator/blob/master/src/main/resources/schema/sparkCluster.json#L18).

is there another location where the image is being specified in the schema? all i am seeing is that `customImage` key, and my understanding is that it will get the default value if the user doesn't specify anything.

**Comment by elmiko** [comment]
maybe i am missing something fundamental, but it doesn't look like there is an easy way to change the getter function that is created by the yaml2pojo parsing stuff. but i don't know that package well, so i am willing to accept that there is a detail here i am probably skipping.

**Comment by Jiri-Kremser** [comment]
You are right, it's not easy to figure out that CR was created w/o the explicit `customImage`, because of the way how the class was generated and the default is populated.

**Comment by Jiri-Kremser** [comment]
Perhaps, we can get rid of the default that comes from the JSON schema completely and have only the default defined by the env. variable and that explicit way using the `customImage` in CR.

If the env. variable is not set and neither the `customImage` is set, we can take the default from a constant from the Java code.

What do you think, would it be confusing? It would behave as I've described in those 4 points, but the internal implementation would be slightly different.

**Comment by elmiko** [comment]
i think removing the default from the schema is probably the right way forward, we can then choose between the env variable and either something in the code or perhaps on the deployment for the operator itself?

**Comment by Jiri-Kremser** [comment]
:+1:  env. variable for the operator is probably the best place (the deployment resource), because it's a global feature for the whole operator

**Comment by elmiko** [comment]
sgtm, i'll work up a pr =)

**Comment by Jiri-Kremser** [comment]
> can this be updated to use the same 2.4 image as the clusters?

there was some issue with this image, it just didn't work but I don't recall the details... I think the entrypoint or launch script was different and didn't work with the `spark-submit --master=k8s://..`

> it looks like SparkApplications operate in spark's scheduled mode (as opposed to standalone), should we have an alternate env variable for SparkApplication images?

Good question. Probably yes, you mean for the _default_ spark application images, right? I think, it's better to de-couple it.

**Comment by elmiko** [comment]
> Probably yes, you mean for the default spark application images, right? I think, it's better to de-couple it.

right, should we make this part of the schema behave more like it does in SparkCluster, except with a different env variable.

```
    "image": {
      "type": "string",
      "default": "quay.io/jkremser/openshift-spark:2.3-latest"
},
```

**Comment by Jiri-Kremser** [comment]
yes, that would be ideal

the snippet you have posted is already in the json schema for spark apps: https://github.com/radanalyticsio/spark-operator/blob/master/src/main/resources/schema/sparkApplication.json#L57
and it should be deleted, because if it's there, we can't tell if user actually specified the custom image in the CR or if it comes from the default value.

So following the same precedence rules as for the spark cluster is probably the cleanest way to this.

..and introducing a new env variable, something like `DEFAULT_SPARK_APP(LICATION?)_IMAGE`

**Comment by elmiko** [comment]
ok, great. sounds like we are on the same page =)

**Comment by Jiri-Kremser** [comment]
done in #204 and #194 by @elmiko
