### ISSUE TITLE
create a `stable` tag for spark-operator images

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/spark-operator#197]
### Description:
the spark-operator is similar to several other radanalytics projects and includes some of their work as images. it can often be difficult to understand which versions of the underlying frameworks are included with any given tag for a container image.

to help make spark-operator more similar to the other radanalytics image releases and to help make the known versions easier to ingest, i would like to propose creating a `stable` tag for the spark-operator image.

this tag would contain the same versions of spark and related libraries that are currently included in the oshinko `stable` tags and will make it easier to consume cross-project efforts like oshinko s2i.

**Comment by Jiri-Kremser** [comment]
Currently, there isn't any dependency on other projects from radanalytics other than the container image and spark-operator in version X should work with any version Y of the `openshift-spark`, currently there isn't any direct dependency on the REST API or anything like that so luckily we can mix and match the version pretty much arbitrarily.

`stable`:
Ideally the `:latest-released` should conceptually match the `:stable` from your description. When putting stable on one version, it implicitly puts "unstable" to the rest or at least that's how I read it :)

When looking into tags on https://hub.docker.com/r/radanalyticsio/openshift-spark/tags I can't see any `:stable` tag.

In general I am not against it. If you think that introducing yet another tag will make the versions easier to ingest, why not. Other thing that may help with "observability", like what versions of what are actually in a container image, is using the right [labels](https://github.com/radanalyticsio/spark-operator/blob/master/Dockerfile.centos#L5) correctly. I want the default option that is in the manifest (I.e.  the `:lastest-released`) to deploy Spark@2.4 by default. Also encoding everything into the container image tag is insane. You know like `:centos8-scala2.11-spark42-hadoop34-java8-operator42`. imho goal isn't supporting every combination of those frameworks, but rather provide somewhat opinionated way of things that works together. From this POV the `:stable` makes sense.


> to consume cross-project efforts like oshinko s2i.

This is not going to happen or at least not with the standard OpenShift specific s2i tooling. Spark-operator has been from the beginning designed as Kubernetes first and anything that is OpenShift specific has to be either done by K8s primitives or unsupported. The idea is to avoid vendor lock-in and allow users to freely migrate among all K8s distributions. I was exploring the idea of knative builds and achieving the same stuff as with s2i and this is a way to go.
Or another (μService) operator whose only job is to take a repo url or directly the code (w/ notebook or some simple python or scala script) and create the image.

**Comment by elmiko** [comment]
> Currently, there isn't any dependency on other projects from radanalytics ...

i was actually thinking more the _other_ way, if i want to use other radanalytics projects with the spark operator i want to make sure that the installed versions of everything will match up.

> `stable`:
Ideally the `:latest-released` should conceptually match the `:stable` from your description. When putting stable on one version, it implicitly puts "unstable" to the rest or at least that's how I read it :)

this makes good sense to me, and i think _ideally_ we will have `:latest` and that will be our latest released version. i think this would be fine, perhaps we would just need a `:master` or something. i'm not sure that naming-wise having `:latest` and `:latest-released` will be the best in the end. it would be great if `:latest` was just our latest release.

> When looking into tags on https://hub.docker.com/r/radanalyticsio/openshift-spark/tags I can't see any `:stable` tag.

correct, i was thinking for the oshinko tooling where we have the `:stable` tag to help ensure that the packaged components are from a known source.

> If you think that introducing yet another tag will make the versions easier to ingest, why not.

i'm not entirely convinced that we need it, but i wanted to start the conversation. i am starting to field support questions from folks who are attempting to integrate things like the oshinko-s2i with spark-operator deployed clusters and it is showing some of the weaknesses in the tool chain from a user perspective.

> I want the default option that is in the manifest (I.e. the `:lastest-released`) to deploy Spark@2.4 by default.

this is at the heart of the tag naming for me, i think we need to have a consistent spark image for _all_ the radanalytics pieces that can work together as an "out of the box" experience. for example, as a user if i get all the `:latest` tags for spark-operator and oshinko-s2i, then i should know that whatever i deploy will work together at the spark level. this is my big concern.

> Also encoding everything into the container image tag is insane. You know like `:centos8-scala2.11-spark42-hadoop34-java8-operator42`.

totally agree

>  imho goal isn't supporting every combination of those frameworks, but rather provide somewhat opinionated way of things that works together.

agreed, and this is my concern as well. getting all the things to play nice out of the box.

> This is not going to happen or at least not with the standard OpenShift specific s2i tooling.

i have issue with this. the current oshinko-s2i tooling allows me to specify a cluster name when launching my application, i think at the minimum when someone is using tooling that comes from radanalytics at a specific release tag (eg `:latest` or `:stable` or `:foo-bar`) that all the pieces should work together at the spark level.

> Spark-operator has been from the beginning designed as Kubernetes first and anything that is OpenShift specific has to be either done by K8s primitives or unsupported.

ack, while i think OpenShift should be a first-class citizen i can understand not wanting to put primitives in that will cause breakage with Kubernetes.

**Comment by elmiko** [comment]
i think we've had a good discussion about this, i don't think the `stable` tag is necessary for now. i would like to close this issue unless you have objections @Jiri-Kremser ?

**Comment by Jiri-Kremser** [comment]
no objections :+1: 
btw. my objections weren't about using oshinko-s2i with spark operator in general. That's perfectly fine provided `oshinko-s2i` calls/uses spark-operator. I was more worried about the other direction i.e. calling `oshinko-s2i` from the operator, because that would break the "always run on vanilla K8s" promise. Also it would be different story if `oshinko-s2i` was built on top of knative builds.

**Comment by elmiko** [comment]
yeah, i know you weren't objecting to using oshinko with spark-operator.

i totally agree with the desire to make this always run on the widest variety of kubernetes available (i am starting not to believe in "vanilla"). i also agree that we should not bake "oshinko" specific options into the operator. i think you've done a great job of making sure that the facilities are available for oshinko to consume the operator, that is perfect in my book.
