### ISSUE TITLE
Should defaults be included in the schema that gets applied to kubernetes?

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/spark-operator#215]
### Description:

When consuming `SparkCluster` objects that have been created by the operator, there are some values which are considered default that do not get replicated in the output.

for example, the `sparkWebUI` field defaults to `true`, but if it is not specified in the creation schema then it is not displayed on output (eg `kubectl describe sparkcluster foo`).

this discrepancy creates an issue for downstream tooling in that there is no way to know which options have been created on a cluster without synchronizing the defaults across projects (eg kubectl plugin needs to know what the operator uses as default).

i am wondering if we should consider having the operator create a full schema with all the options when it applies the manifest to kubernetes?

**Comment by Jiri-Kremser** [comment]
operator actually creates the k8s resources with all the information, what it doesn't do is modifying the CRs / CMs. It would create a new event (potentially even loop) and some special treatment with this new event, like operator pls ignore it, because it's nothing new, we only filled in the default values, imho, over-complicated

a way to go would be reading the defaults from the CRD

**Comment by elmiko** [comment]
> a way to go would be reading the defaults from the CRD

ok, this makes good sense. do you know how to get that info back from kubernetes?

i tried doing `kubectl describe crd sparkcluster` but i don't see the default values.

```
Name:         sparkclusters.radanalytics.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-03-25T17:50:15Z
  Generation:          1
  Resource Version:    19029892
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/sparkclusters.radanalytics.io
  UID:                 723de7fe-4f26-11e9-9d70-c85b76d0fbda
Spec:
  Additional Printer Columns:
    JSON Path:    .metadata.creationTimestamp
    Description:  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    Name:  Age
    Type:  date
  Group:   radanalytics.io
  Names:
    Kind:       SparkCluster
    List Kind:  SparkClusterList
    Plural:     sparkclusters
    Singular:   sparkcluster
  Scope:        Namespaced
  Version:      v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       SparkCluster
    List Kind:  SparkClusterList
    Plural:     sparkclusters
    Singular:   sparkcluster
  Conditions:
    Last Transition Time:  2019-03-25T17:50:15Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>
```

**Comment by Jiri-Kremser** [comment]
I think, there is a bug in there. The schema should be there, but it's missing.

**Comment by elmiko** [comment]
ok, thanks for the info Jirka. i'm going to close this out as i think the solution lies with other tools and not the operator.
