### ISSUE TITLE
starting the operator throws error

### ISSUE THREAD

**Issue by dwai1714** [radanalyticsio/spark-operator#260]
kubectl apply -f manifest/operator.yaml 
serviceaccount/spark-operator created
clusterrolebinding.rbac.authorization.k8s.io/spark-operator-edit-resources configured
deployment.apps/spark-operator created

### Description:
The operator pod starts and dies immediately. The log is :
Failure executing: GET at: https://172.30.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:dc-try:spark-operator" cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope: User "system:serviceaccount:dc-try:spark-operator" cannot list all customresourcedefinitions.apiextensions.k8s.io in the cluster.

#### Steps to reproduce:

  1. start minishift 3.11
  2. login as developer
  3. login -u sytem:admin
  4. kubectl apply -f manifest/operator.yaml 
  6. Go to the created pod
  7. Open logs

**Comment by elmiko** [comment]
hi @dwai1714 , it seems like the service account does not have sufficient privileges to list the custom resources. i'm not sure why though, the operator.yaml _should_ configure the service account with cluster-admin privileges.

as a workaround, you could try manually applying the custom resource definitions and then restart the operator. to do this you will need to login as a cluster-admin and the do the following:

```
oc apply -f manifest/olm/crd/sparkapplication.crd.yaml
oc apply -f manifest/olm/crd/sparkcluster.crd.yaml
```

not a perfect solution, but it might get you running. it seems like the deeper issue is that the service account is not getting the proper role.

**Comment by jkremser** [comment]
hello @dwai1714 
either switch the namespace from `dc-try` to `default` when deploying it, or change it to `dc-try` in the `operator.yaml` [here](https://github.com/radanalyticsio/spark-operator/blob/da46a8161f00d821997c3e178e0606afdb1531bf/manifest/operator.yaml#L18)

If you apply the `operator.yaml` in a namespace, it will create those resources in that namespace, however the `ClusterRoleBinding` requires to fully qualify the security account and we have the system:serviceaccount:default:spark-operator hard-code here.

**Comment by dwai1714** [comment]
Hi @jkremser 
The way it worked was changing the "default" to the namespace where I am running the operator.
If I leave it as default then it gives me the same error.
I was running the operator as admin though.
Thanks

**Comment by elmiko** [comment]
glad you got it working @dwai1714

**Comment by dwai1714** [comment]
Thanks @jkremser and @elmiko
