### ISSUE TITLE
Spark-Operator-Azure-Datalake

### ISSUE THREAD

**Issue by polyzos** [radanalyticsio/spark-operator#265]
Can't Connect to azure blob storage using the spark-operator

Im using the spark-operator and im trying to connect to the azure blob storage
```
spark.read.load("wasbs://.../")
```
However i always get the same exception
`Exception in thread "main" java.io.IOException: No FileSystem for scheme: wasbs`

Configurations on the spark side are also set:
("fs.azure", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
(fs.azure.account.key.<account>.blob.core.windows.net", "<secret>")

I tried all the solutions i found online and even though it works for everyone, we had no luck.
So im starting to think if it could be an issue with the operator.

Connections to our datalake through zeppelin and azure databricks work fine and the difference is that both of those have hadoop, but the operator doesn't.
Could this be the potential issue?

**Comment by elmiko** [comment]
hi @polyzos, thanks for raising the issue.

i am not very familiar with azure blob storage, but i wanted to address you last question:

> Connections to our datalake through zeppelin and azure databricks work fine and the difference is that both of those have hadoop, but the operator doesn't.
> Could this be the potential issue?

so, the operator itself does not contain hadoop or spark, it is simply the tooling that deploys a spark cluster.

the spark cluster images that are used by default[0] do contain hadoop packaged as a binary from the upstream source at spark.apache.org. the version of hadoop is 2.7.3, is it possible that this version of hadoop does not contain the schema for `wasbs://` URIs?

[0] https://quay.io/repository/radanalyticsio/openshift-spark

**Comment by polyzos** [comment]
I don't think the hadoop version is the issue, we have connected with this version as well.

**Comment by elmiko** [comment]
ok, so it sounds like the spark cluster image might not be the issue. could you share the manifest you used to deploy the cluster?

also, how are you accessing the spark cluster? (eg application, notebook, spark-submit, etc)

**Comment by polyzos** [comment]
It seems that the issue was how hadoop was configured in the image by default.. We had to manually add some jars and set some hadoop configuration paths.

**Comment by elmiko** [comment]
thanks for the update, glad to hear to found the issue!
