### ISSUE TITLE
The node was low on resource: ephemeral-storage. Container spark-kubernetes-executor was using 107260Ki, which exceeds its request of 0. 

### ISSUE THREAD

**Issue by krisshub** [radanalyticsio/spark-operator#295]
I am getting the below error during execution of spark executors

Job aborted due to stage failure: Task 55 in stage 0.0 failed 4 times, most recent failure: Lost task 55.3 in stage 0.0 (TID 142, 100.124.201.135, executor 10): ExecutorLostFailure (executor 10 exited caused by one of the running tasks) Reason: 
The executor with id 10 exited with exit code -1.
The API gave the following brief reason: Evicted
The API gave the following message: The node was low on resource: ephemeral-storage. Container spark-kubernetes-executor was using 107260Ki, which exceeds its request of 0. 

Below is the configuration used: 

apiVersion: radanalytics.io/v1
kind: SparkApplication
metadata:
  name: xxx
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "xxx"
  imagePullPolicy: Always
  mainClass: xxx
  mainApplicationFile: xxx
  arguments: xxx
  restartPolicy: Never
  sparkVersion: "3.0.0"
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2048m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 2
    coreLimit: "2000m"
    memory: "8192m"
    instances: 24
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

How can i configure the "ephemeral-storage"?

**Comment by pjonnalahub** [comment]
> I am getting the below error during execution of spark executors
> 
> Job aborted due to stage failure: Task 55 in stage 0.0 failed 4 times, most recent failure: Lost task 55.3 in stage 0.0 (TID 142, 100.124.201.135, executor 10): ExecutorLostFailure (executor 10 exited caused by one of the running tasks) Reason:
> The executor with id 10 exited with exit code -1.
> The API gave the following brief reason: Evicted
> The API gave the following message: The node was low on resource: ephemeral-storage. Container spark-kubernetes-executor was using 107260Ki, which exceeds its request of 0.
> 
> Below is the configuration used:
> 
> apiVersion: radanalytics.io/v1
> kind: SparkApplication
> metadata:
> name: xxx
> namespace: default
> spec:
> type: Scala
> mode: cluster
> image: "xxx"
> imagePullPolicy: Always
> mainClass: xxx
> mainApplicationFile: xxx
> arguments: xxx
> restartPolicy: Never
> sparkVersion: "3.0.0"
> volumes:
> - name: "test-volume"
> hostPath:
> path: "/tmp"
> type: Directory
> driver:
> cores: 1
> coreLimit: "1200m"
> memory: "2048m"
> labels:
> version: 3.0.0
> volumeMounts:
> - name: "test-volume"
> mountPath: "/tmp"
> executor:
> cores: 2
> coreLimit: "2000m"
> memory: "8192m"
> instances: 24
> labels:
> version: 3.0.0
> volumeMounts:
> - name: "test-volume"
> mountPath: "/tmp"
> 
> How can i configure the "ephemeral-storage"?

Hi Krisshub, did you figure out how to configure ephemeral storage?
