### ISSUE TITLE
have some resource limit for the operator itself in the manifest

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#82]
If the cluster defautls are too low, it will 'crashloop'

**Comment by sharebear** [comment]
What would be sane default values here?

**Comment by sharebear** [comment]
Just realised that this is a java application so the memory limit needs to correlate with the Xmx setting on the JVM. I see now that there is no Xmx parameter passed to the operator JVM this means that on java <= 8 it will not respect the limits in the cgroups and set a default Xmx based on the max memory on the docker/k8s/os node.

Interstingly the fabric8 image has a workaround for this in it's run-java.sh script with the `JAVA_MAX_MEM_RATIO` configuration but this is not in use in the operator dockerfile which execs the jvm directly.

Therefore for the solution to this issue to be effective it should also include either explicitly setting Xmx on the java call (or though the JAVA_TOOL_OPTS env var) or changing the command in the Dockerfile to make use of the provided `run-java.sh` script.

**Comment by Jiri-Kremser** [comment]
Thanks for looking.

It should be using that cgroups limit, because the `UseCGroupMemoryLimitForHeap` and `UnlockExperimentalVMOptions` are both [set](https://github.com/radanalyticsio/spark-operator/blob/master/Dockerfile.centos#L3).

"When these two JVM command line options are used, and -Xmx is not specified, the JVM will look at the Linux cgroup configuration, which is what Docker containers use for setting memory limits, to transparently size a maximum Java heap size. FYI, Docker containers also use cgroups configuration for CPU limits too."
--https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

So it should be enough to set the sane values in the yaml descriptor in here:

https://github.com/radanalyticsio/spark-operator/blob/master/manifest/operator.yaml#L35

```
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

**Comment by sharebear** [comment]
> It should be using that cgroups limit, because the UseCGroupMemoryLimitForHeap and UnlockExperimentalVMOptions are both set.

Good point, never used experimental options in prod myself so I overlooked those.Then it should indeed be a very small PR, should manage that tonight.

**Comment by Jiri-Kremser** [comment]
done in #106
